[package]
name = "ttdl"
version = "0.3.0"
authors = ["Vladimir Markelov <vmatroskin@gmail.com>"]
edition = "2018"
keywords = ["todotxt", "terminal", "cli", "todo"]
license = "MIT"
description = "TTDL - Terminal ToDo List manager"
readme = "README.md"
repository = "https://github.com/VladimirMarkelov/ttdl"

[profile.release]
lto = true

[dependencies]
todo_lib = "0.2.0"
getopts = "0.2"
chrono = "^0.4"
textwrap = "0.11"
lazy_static = "1.0"
caseless = "0.2.1"
dirs = "1.0"
toml = "0.4"
atty = "0.2"
term_size = "0.3.1"
termcolor = "1.0.4"
serde = "1.0"
serde_derive = "1.0.84"

[dependencies.todo-txt]
version = "^1.0"
features = ["extended"]
